// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
  actor_user_id,
  actor_username,
  action,
  resource_type,
  resource_id,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, actor_user_id, actor_username, action, resource_type, resource_id, metadata, created_at
`

type CreateAuditLogParams struct {
	ActorUserID   pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	ActorUsername string      `db:"actor_username" json:"actor_username"`
	Action        string      `db:"action" json:"action"`
	ResourceType  string      `db:"resource_type" json:"resource_type"`
	ResourceID    string      `db:"resource_id" json:"resource_id"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.ActorUsername,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorUsername,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
