// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: auth_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAuthSessions = `-- name: CountActiveAuthSessions :one
SELECT COUNT(*)
FROM auth_sessions
WHERE revoked_at IS NULL
  AND expires_at > NOW()
  AND idle_expires_at > NOW()
`

func (q *Queries) CountActiveAuthSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAuthSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAuthSessionsByUserID = `-- name: CountActiveAuthSessionsByUserID :one
SELECT COUNT(*)
FROM auth_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
  AND idle_expires_at > NOW()
`

type CountActiveAuthSessionsByUserIDParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CountActiveAuthSessionsByUserID(ctx context.Context, arg CountActiveAuthSessionsByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAuthSessionsByUserID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
  user_id,
  client_name,
  user_agent,
  refresh_token_hash,
  refresh_token_family_id,
  last_used_at,
  expires_at,
  idle_expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
`

type CreateAuthSessionParams struct {
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	ClientName           string             `db:"client_name" json:"client_name"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	RefreshTokenHash     string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenFamilyID pgtype.UUID        `db:"refresh_token_family_id" json:"refresh_token_family_id"`
	LastUsedAt           pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.ClientName,
		arg.UserAgent,
		arg.RefreshTokenHash,
		arg.RefreshTokenFamilyID,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.RefreshTokenFamilyID,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM auth_sessions
WHERE id = $1
LIMIT 1
`

type GetAuthSessionByIDParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAuthSessionByID(ctx context.Context, arg GetAuthSessionByIDParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, arg.ID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.RefreshTokenFamilyID,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByRefreshTokenHash = `-- name: GetAuthSessionByRefreshTokenHash :one
SELECT id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM auth_sessions
WHERE refresh_token_hash = $1
LIMIT 1
`

type GetAuthSessionByRefreshTokenHashParams struct {
	RefreshTokenHash string `db:"refresh_token_hash" json:"refresh_token_hash"`
}

func (q *Queries) GetAuthSessionByRefreshTokenHash(ctx context.Context, arg GetAuthSessionByRefreshTokenHashParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByRefreshTokenHash, arg.RefreshTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.RefreshTokenFamilyID,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAuthSessionsByUserPage = `-- name: ListActiveAuthSessionsByUserPage :many
SELECT id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM auth_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
  AND idle_expires_at > NOW()
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListActiveAuthSessionsByUserPageParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	OffsetCount int32       `db:"offset_count" json:"offset_count"`
	LimitCount  int32       `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListActiveAuthSessionsByUserPage(ctx context.Context, arg ListActiveAuthSessionsByUserPageParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listActiveAuthSessionsByUserPage, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.UserAgent,
			&i.RefreshTokenHash,
			&i.RefreshTokenFamilyID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAuthSessionsPage = `-- name: ListActiveAuthSessionsPage :many
SELECT id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM auth_sessions
WHERE revoked_at IS NULL
  AND expires_at > NOW()
  AND idle_expires_at > NOW()
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $1
`

type ListActiveAuthSessionsPageParams struct {
	OffsetCount int32 `db:"offset_count" json:"offset_count"`
	LimitCount  int32 `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListActiveAuthSessionsPage(ctx context.Context, arg ListActiveAuthSessionsPageParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listActiveAuthSessionsPage, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.UserAgent,
			&i.RefreshTokenHash,
			&i.RefreshTokenFamilyID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthSessions = `-- name: ListAuthSessions :many
SELECT id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM auth_sessions
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAuthSessions(ctx context.Context) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listAuthSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.UserAgent,
			&i.RefreshTokenHash,
			&i.RefreshTokenFamilyID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthSessionsByUserID = `-- name: ListAuthSessionsByUserID :many
SELECT id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
FROM auth_sessions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

type ListAuthSessionsByUserIDParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListAuthSessionsByUserID(ctx context.Context, arg ListAuthSessionsByUserIDParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listAuthSessionsByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.UserAgent,
			&i.RefreshTokenHash,
			&i.RefreshTokenFamilyID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllActiveAuthSessions = `-- name: RevokeAllActiveAuthSessions :execrows
UPDATE auth_sessions
SET
  revoked_at = NOW(),
  revoke_reason = $1,
  updated_at = NOW()
WHERE revoked_at IS NULL
  AND expires_at > NOW()
  AND idle_expires_at > NOW()
`

type RevokeAllActiveAuthSessionsParams struct {
	RevokeReason string `db:"revoke_reason" json:"revoke_reason"`
}

func (q *Queries) RevokeAllActiveAuthSessions(ctx context.Context, arg RevokeAllActiveAuthSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllActiveAuthSessions, arg.RevokeReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :one
UPDATE auth_sessions
SET
  revoked_at = NOW(),
  revoke_reason = $1,
  updated_at = NOW()
WHERE id = $2
  AND revoked_at IS NULL
RETURNING id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
`

type RevokeAuthSessionParams struct {
	RevokeReason string      `db:"revoke_reason" json:"revoke_reason"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, revokeAuthSession, arg.RevokeReason, arg.ID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.RefreshTokenFamilyID,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthSessionFamily = `-- name: RevokeAuthSessionFamily :execrows
UPDATE auth_sessions
SET
  revoked_at = NOW(),
  revoke_reason = $1,
  updated_at = NOW()
WHERE refresh_token_family_id = $2
`

type RevokeAuthSessionFamilyParams struct {
	RevokeReason         string      `db:"revoke_reason" json:"revoke_reason"`
	RefreshTokenFamilyID pgtype.UUID `db:"refresh_token_family_id" json:"refresh_token_family_id"`
}

func (q *Queries) RevokeAuthSessionFamily(ctx context.Context, arg RevokeAuthSessionFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionFamily, arg.RevokeReason, arg.RefreshTokenFamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherAuthSessionsForUser = `-- name: RevokeOtherAuthSessionsForUser :execrows
UPDATE auth_sessions
SET
  revoked_at = NOW(),
  revoke_reason = $1,
  updated_at = NOW()
WHERE user_id = $2
  AND revoked_at IS NULL
  AND id <> $3
`

type RevokeOtherAuthSessionsForUserParams struct {
	RevokeReason string      `db:"revoke_reason" json:"revoke_reason"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RevokeOtherAuthSessionsForUser(ctx context.Context, arg RevokeOtherAuthSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherAuthSessionsForUser, arg.RevokeReason, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAuthSession = `-- name: TouchAuthSession :one
UPDATE auth_sessions
SET
  last_used_at = $1,
  idle_expires_at = $2,
  updated_at = NOW()
WHERE id = $3
RETURNING id, user_id, client_name, user_agent, refresh_token_hash, refresh_token_family_id, last_used_at, expires_at, idle_expires_at, revoked_at, revoke_reason, created_at, updated_at
`

type TouchAuthSessionParams struct {
	LastUsedAt    pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	IdleExpiresAt pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	ID            pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, touchAuthSession, arg.LastUsedAt, arg.IdleExpiresAt, arg.ID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.UserAgent,
		&i.RefreshTokenHash,
		&i.RefreshTokenFamilyID,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
