// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_device_authorizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthDeviceAuthorization = `-- name: CreateAuthDeviceAuthorization :one
INSERT INTO auth_device_authorizations (
  device_code,
  user_code,
  client_name,
  requested_scopes,
  expires_at,
  status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, device_code, user_code, client_name, requested_scopes, approved_by_user_id, approved_at, last_polled_at, expires_at, status, created_at, updated_at
`

type CreateAuthDeviceAuthorizationParams struct {
	DeviceCode      string             `db:"device_code" json:"device_code"`
	UserCode        string             `db:"user_code" json:"user_code"`
	ClientName      string             `db:"client_name" json:"client_name"`
	RequestedScopes []string           `db:"requested_scopes" json:"requested_scopes"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status          string             `db:"status" json:"status"`
}

func (q *Queries) CreateAuthDeviceAuthorization(ctx context.Context, arg CreateAuthDeviceAuthorizationParams) (AuthDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, createAuthDeviceAuthorization,
		arg.DeviceCode,
		arg.UserCode,
		arg.ClientName,
		arg.RequestedScopes,
		arg.ExpiresAt,
		arg.Status,
	)
	var i AuthDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.ClientName,
		&i.RequestedScopes,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthDeviceAuthorizationByDeviceCode = `-- name: GetAuthDeviceAuthorizationByDeviceCode :one
SELECT id, device_code, user_code, client_name, requested_scopes, approved_by_user_id, approved_at, last_polled_at, expires_at, status, created_at, updated_at
FROM auth_device_authorizations
WHERE device_code = $1
LIMIT 1
`

type GetAuthDeviceAuthorizationByDeviceCodeParams struct {
	DeviceCode string `db:"device_code" json:"device_code"`
}

func (q *Queries) GetAuthDeviceAuthorizationByDeviceCode(ctx context.Context, arg GetAuthDeviceAuthorizationByDeviceCodeParams) (AuthDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthDeviceAuthorizationByDeviceCode, arg.DeviceCode)
	var i AuthDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.ClientName,
		&i.RequestedScopes,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthDeviceAuthorizationByUserCode = `-- name: GetAuthDeviceAuthorizationByUserCode :one
SELECT id, device_code, user_code, client_name, requested_scopes, approved_by_user_id, approved_at, last_polled_at, expires_at, status, created_at, updated_at
FROM auth_device_authorizations
WHERE user_code = $1
LIMIT 1
`

type GetAuthDeviceAuthorizationByUserCodeParams struct {
	UserCode string `db:"user_code" json:"user_code"`
}

func (q *Queries) GetAuthDeviceAuthorizationByUserCode(ctx context.Context, arg GetAuthDeviceAuthorizationByUserCodeParams) (AuthDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getAuthDeviceAuthorizationByUserCode, arg.UserCode)
	var i AuthDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.ClientName,
		&i.RequestedScopes,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthDeviceAuthorizationStatus = `-- name: UpdateAuthDeviceAuthorizationStatus :one
UPDATE auth_device_authorizations
SET
  status = $1,
  approved_by_user_id = $2,
  approved_at = $3,
  last_polled_at = $4,
  updated_at = NOW()
WHERE id = $5
RETURNING id, device_code, user_code, client_name, requested_scopes, approved_by_user_id, approved_at, last_polled_at, expires_at, status, created_at, updated_at
`

type UpdateAuthDeviceAuthorizationStatusParams struct {
	Status           string             `db:"status" json:"status"`
	ApprovedByUserID pgtype.UUID        `db:"approved_by_user_id" json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	LastPolledAt     pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	ID               pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateAuthDeviceAuthorizationStatus(ctx context.Context, arg UpdateAuthDeviceAuthorizationStatusParams) (AuthDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, updateAuthDeviceAuthorizationStatus,
		arg.Status,
		arg.ApprovedByUserID,
		arg.ApprovedAt,
		arg.LastPolledAt,
		arg.ID,
	)
	var i AuthDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.ClientName,
		&i.RequestedScopes,
		&i.ApprovedByUserID,
		&i.ApprovedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
