// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gizmos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGizmo = `-- name: CreateGizmo :one
INSERT INTO gizmos (
  network_device_id,
  kiosk_url
) VALUES (
  $1,
  $2
)
RETURNING network_device_id, kiosk_url, created_at, updated_at
`

type CreateGizmoParams struct {
	NetworkDeviceID pgtype.UUID `db:"network_device_id" json:"network_device_id"`
	KioskUrl        *string     `db:"kiosk_url" json:"kiosk_url"`
}

func (q *Queries) CreateGizmo(ctx context.Context, arg CreateGizmoParams) (Gizmo, error) {
	row := q.db.QueryRow(ctx, createGizmo, arg.NetworkDeviceID, arg.KioskUrl)
	var i Gizmo
	err := row.Scan(
		&i.NetworkDeviceID,
		&i.KioskUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGizmo = `-- name: DeleteGizmo :exec
DELETE FROM gizmos
WHERE network_device_id = $1
`

type DeleteGizmoParams struct {
	NetworkDeviceID pgtype.UUID `db:"network_device_id" json:"network_device_id"`
}

func (q *Queries) DeleteGizmo(ctx context.Context, arg DeleteGizmoParams) error {
	_, err := q.db.Exec(ctx, deleteGizmo, arg.NetworkDeviceID)
	return err
}

const getGizmoByNetworkDeviceID = `-- name: GetGizmoByNetworkDeviceID :one
SELECT gizmos.network_device_id, gizmos.kiosk_url, gizmos.created_at, gizmos.updated_at, network_devices.id, network_devices.mac_address, network_devices.display_name, network_devices.vlan_id, network_devices.created_by_user_id, network_devices.updated_by_user_id, network_devices.created_at, network_devices.updated_at, network_devices.disabled, vlans.vlan_id, vlans.name, vlans.description, vlans.created_at, vlans.updated_at
FROM gizmos
JOIN network_devices ON network_devices.id = gizmos.network_device_id
JOIN vlans ON vlans.vlan_id = network_devices.vlan_id
WHERE gizmos.network_device_id = $1
LIMIT 1
`

type GetGizmoByNetworkDeviceIDParams struct {
	NetworkDeviceID pgtype.UUID `db:"network_device_id" json:"network_device_id"`
}

type GetGizmoByNetworkDeviceIDRow struct {
	Gizmo         Gizmo         `db:"gizmo" json:"gizmo"`
	NetworkDevice NetworkDevice `db:"network_device" json:"network_device"`
	Vlan          Vlan          `db:"vlan" json:"vlan"`
}

func (q *Queries) GetGizmoByNetworkDeviceID(ctx context.Context, arg GetGizmoByNetworkDeviceIDParams) (GetGizmoByNetworkDeviceIDRow, error) {
	row := q.db.QueryRow(ctx, getGizmoByNetworkDeviceID, arg.NetworkDeviceID)
	var i GetGizmoByNetworkDeviceIDRow
	err := row.Scan(
		&i.Gizmo.NetworkDeviceID,
		&i.Gizmo.KioskUrl,
		&i.Gizmo.CreatedAt,
		&i.Gizmo.UpdatedAt,
		&i.NetworkDevice.ID,
		&i.NetworkDevice.MacAddress,
		&i.NetworkDevice.DisplayName,
		&i.NetworkDevice.VlanID,
		&i.NetworkDevice.CreatedByUserID,
		&i.NetworkDevice.UpdatedByUserID,
		&i.NetworkDevice.CreatedAt,
		&i.NetworkDevice.UpdatedAt,
		&i.NetworkDevice.Disabled,
		&i.Vlan.VlanID,
		&i.Vlan.Name,
		&i.Vlan.Description,
		&i.Vlan.CreatedAt,
		&i.Vlan.UpdatedAt,
	)
	return i, err
}

const getKioskURLByMAC = `-- name: GetKioskURLByMAC :one
SELECT gizmos.kiosk_url
FROM gizmos
JOIN network_devices ON network_devices.id = gizmos.network_device_id
WHERE network_devices.mac_address = $1
  AND network_devices.disabled = false
  AND gizmos.kiosk_url IS NOT NULL
LIMIT 1
`

type GetKioskURLByMACParams struct {
	MacAddress string `db:"mac_address" json:"mac_address"`
}

func (q *Queries) GetKioskURLByMAC(ctx context.Context, arg GetKioskURLByMACParams) (*string, error) {
	row := q.db.QueryRow(ctx, getKioskURLByMAC, arg.MacAddress)
	var kiosk_url *string
	err := row.Scan(&kiosk_url)
	return kiosk_url, err
}

const listGizmos = `-- name: ListGizmos :many
SELECT gizmos.network_device_id, gizmos.kiosk_url, gizmos.created_at, gizmos.updated_at, network_devices.id, network_devices.mac_address, network_devices.display_name, network_devices.vlan_id, network_devices.created_by_user_id, network_devices.updated_by_user_id, network_devices.created_at, network_devices.updated_at, network_devices.disabled, vlans.vlan_id, vlans.name, vlans.description, vlans.created_at, vlans.updated_at
FROM gizmos
JOIN network_devices ON network_devices.id = gizmos.network_device_id
JOIN vlans ON vlans.vlan_id = network_devices.vlan_id
ORDER BY network_devices.display_name, network_devices.id
`

type ListGizmosRow struct {
	Gizmo         Gizmo         `db:"gizmo" json:"gizmo"`
	NetworkDevice NetworkDevice `db:"network_device" json:"network_device"`
	Vlan          Vlan          `db:"vlan" json:"vlan"`
}

func (q *Queries) ListGizmos(ctx context.Context) ([]ListGizmosRow, error) {
	rows, err := q.db.Query(ctx, listGizmos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGizmosRow{}
	for rows.Next() {
		var i ListGizmosRow
		if err := rows.Scan(
			&i.Gizmo.NetworkDeviceID,
			&i.Gizmo.KioskUrl,
			&i.Gizmo.CreatedAt,
			&i.Gizmo.UpdatedAt,
			&i.NetworkDevice.ID,
			&i.NetworkDevice.MacAddress,
			&i.NetworkDevice.DisplayName,
			&i.NetworkDevice.VlanID,
			&i.NetworkDevice.CreatedByUserID,
			&i.NetworkDevice.UpdatedByUserID,
			&i.NetworkDevice.CreatedAt,
			&i.NetworkDevice.UpdatedAt,
			&i.NetworkDevice.Disabled,
			&i.Vlan.VlanID,
			&i.Vlan.Name,
			&i.Vlan.Description,
			&i.Vlan.CreatedAt,
			&i.Vlan.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGizmo = `-- name: UpdateGizmo :one
UPDATE gizmos
SET kiosk_url = $1
WHERE network_device_id = $2
RETURNING network_device_id, kiosk_url, created_at, updated_at
`

type UpdateGizmoParams struct {
	KioskUrl        *string     `db:"kiosk_url" json:"kiosk_url"`
	NetworkDeviceID pgtype.UUID `db:"network_device_id" json:"network_device_id"`
}

func (q *Queries) UpdateGizmo(ctx context.Context, arg UpdateGizmoParams) (Gizmo, error) {
	row := q.db.QueryRow(ctx, updateGizmo, arg.KioskUrl, arg.NetworkDeviceID)
	var i Gizmo
	err := row.Scan(
		&i.NetworkDeviceID,
		&i.KioskUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
