// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ActorUserID   pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	ActorUsername string             `db:"actor_username" json:"actor_username"`
	Action        string             `db:"action" json:"action"`
	ResourceType  string             `db:"resource_type" json:"resource_type"`
	ResourceID    string             `db:"resource_id" json:"resource_id"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthDeviceAuthorization struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	DeviceCode       string             `db:"device_code" json:"device_code"`
	UserCode         string             `db:"user_code" json:"user_code"`
	ClientName       string             `db:"client_name" json:"client_name"`
	RequestedScopes  []string           `db:"requested_scopes" json:"requested_scopes"`
	ApprovedByUserID pgtype.UUID        `db:"approved_by_user_id" json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	LastPolledAt     pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status           string             `db:"status" json:"status"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuthSession struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	ClientName           string             `db:"client_name" json:"client_name"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	RefreshTokenHash     string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenFamilyID pgtype.UUID        `db:"refresh_token_family_id" json:"refresh_token_family_id"`
	LastUsedAt           pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason         string             `db:"revoke_reason" json:"revoke_reason"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type NetworkDevice struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	MacAddress      string             `db:"mac_address" json:"mac_address"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	VlanID          int32              `db:"vlan_id" json:"vlan_id"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `db:"updated_by_user_id" json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Disabled        bool               `db:"disabled" json:"disabled"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Username  string             `db:"username" json:"username"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Groups    []string           `db:"groups" json:"groups"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Vlan struct {
	VlanID      int32              `db:"vlan_id" json:"vlan_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
