// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ActorUserID   pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	ActorUsername string             `db:"actor_username" json:"actor_username"`
	Action        string             `db:"action" json:"action"`
	ResourceType  string             `db:"resource_type" json:"resource_type"`
	ResourceID    string             `db:"resource_id" json:"resource_id"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthDeviceAuthorization struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	DeviceCode       string             `db:"device_code" json:"device_code"`
	UserCode         string             `db:"user_code" json:"user_code"`
	ClientName       string             `db:"client_name" json:"client_name"`
	RequestedScopes  []string           `db:"requested_scopes" json:"requested_scopes"`
	ApprovedByUserID pgtype.UUID        `db:"approved_by_user_id" json:"approved_by_user_id"`
	ApprovedAt       pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	LastPolledAt     pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status           string             `db:"status" json:"status"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuthSession struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	ClientName           string             `db:"client_name" json:"client_name"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	RefreshTokenHash     string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	RefreshTokenFamilyID pgtype.UUID        `db:"refresh_token_family_id" json:"refresh_token_family_id"`
	LastUsedAt           pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason         string             `db:"revoke_reason" json:"revoke_reason"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Nas struct {
	ID              int64   `db:"id" json:"id"`
	Nasname         string  `db:"nasname" json:"nasname"`
	Shortname       string  `db:"shortname" json:"shortname"`
	Type            string  `db:"type" json:"type"`
	Ports           *int32  `db:"ports" json:"ports"`
	Secret          string  `db:"secret" json:"secret"`
	Server          *string `db:"server" json:"server"`
	Community       *string `db:"community" json:"community"`
	Description     *string `db:"description" json:"description"`
	RequireMa       string  `db:"require_ma" json:"require_ma"`
	LimitProxyState string  `db:"limit_proxy_state" json:"limit_proxy_state"`
}

type Nasreload struct {
	Nasipaddress netip.Addr         `db:"nasipaddress" json:"nasipaddress"`
	Reloadtime   pgtype.Timestamptz `db:"reloadtime" json:"reloadtime"`
}

type NetworkDevice struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	MacAddress      string             `db:"mac_address" json:"mac_address"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	VlanID          int32              `db:"vlan_id" json:"vlan_id"`
	CreatedByUserID pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID        `db:"updated_by_user_id" json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PresenceClient struct {
	ID                     pgtype.UUID        `db:"id" json:"id"`
	MacAddress             string             `db:"mac_address" json:"mac_address"`
	NetworkDeviceID        pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	Status                 string             `db:"status" json:"status"`
	FirstSeenAt            pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt             pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	LastSourceKey          string             `db:"last_source_key" json:"last_source_key"`
	LastSourceType         string             `db:"last_source_type" json:"last_source_type"`
	LastMedium             string             `db:"last_medium" json:"last_medium"`
	LastObservationPointID pgtype.UUID        `db:"last_observation_point_id" json:"last_observation_point_id"`
	LastSsid               *string            `db:"last_ssid" json:"last_ssid"`
	LastMetadata           []byte             `db:"last_metadata" json:"last_metadata"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PresenceObservationPoint struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SourceKey        string             `db:"source_key" json:"source_key"`
	SourceType       string             `db:"source_type" json:"source_type"`
	Medium           string             `db:"medium" json:"medium"`
	ExternalID       string             `db:"external_id" json:"external_id"`
	ParentExternalID string             `db:"parent_external_id" json:"parent_external_id"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	LocationLabel    string             `db:"location_label" json:"location_label"`
	Notes            string             `db:"notes" json:"notes"`
	Ssid             *string            `db:"ssid" json:"ssid"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PresenceSession struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	SourceKey          string             `db:"source_key" json:"source_key"`
	SourceType         string             `db:"source_type" json:"source_type"`
	Medium             string             `db:"medium" json:"medium"`
	SourceSessionKey   string             `db:"source_session_key" json:"source_session_key"`
	ClientMacAddress   string             `db:"client_mac_address" json:"client_mac_address"`
	NetworkDeviceID    pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	ObservationPointID pgtype.UUID        `db:"observation_point_id" json:"observation_point_id"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	SourceUpdatedAt    pgtype.Timestamptz `db:"source_updated_at" json:"source_updated_at"`
	LastSeenAt         pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	EndedAt            pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	Ssid               *string            `db:"ssid" json:"ssid"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PresenceWorkerState struct {
	WorkerName      string             `db:"worker_name" json:"worker_name"`
	SourceKey       string             `db:"source_key" json:"source_key"`
	State           []byte             `db:"state" json:"state"`
	LastPolledAt    pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	LastSucceededAt pgtype.Timestamptz `db:"last_succeeded_at" json:"last_succeeded_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Radacct struct {
	Radacctid           int64              `db:"radacctid" json:"radacctid"`
	Acctsessionid       string             `db:"acctsessionid" json:"acctsessionid"`
	Acctuniqueid        string             `db:"acctuniqueid" json:"acctuniqueid"`
	Username            *string            `db:"username" json:"username"`
	Groupname           *string            `db:"groupname" json:"groupname"`
	Realm               *string            `db:"realm" json:"realm"`
	Nasipaddress        netip.Addr         `db:"nasipaddress" json:"nasipaddress"`
	Nasportid           *string            `db:"nasportid" json:"nasportid"`
	Nasporttype         *string            `db:"nasporttype" json:"nasporttype"`
	Acctstarttime       pgtype.Timestamptz `db:"acctstarttime" json:"acctstarttime"`
	Acctupdatetime      pgtype.Timestamptz `db:"acctupdatetime" json:"acctupdatetime"`
	Acctstoptime        pgtype.Timestamptz `db:"acctstoptime" json:"acctstoptime"`
	Acctinterval        *int64             `db:"acctinterval" json:"acctinterval"`
	Acctsessiontime     *int64             `db:"acctsessiontime" json:"acctsessiontime"`
	Acctauthentic       *string            `db:"acctauthentic" json:"acctauthentic"`
	ConnectinfoStart    *string            `db:"connectinfo_start" json:"connectinfo_start"`
	ConnectinfoStop     *string            `db:"connectinfo_stop" json:"connectinfo_stop"`
	Acctinputoctets     *int64             `db:"acctinputoctets" json:"acctinputoctets"`
	Acctoutputoctets    *int64             `db:"acctoutputoctets" json:"acctoutputoctets"`
	Calledstationid     *string            `db:"calledstationid" json:"calledstationid"`
	Callingstationid    *string            `db:"callingstationid" json:"callingstationid"`
	Acctterminatecause  *string            `db:"acctterminatecause" json:"acctterminatecause"`
	Servicetype         *string            `db:"servicetype" json:"servicetype"`
	Framedprotocol      *string            `db:"framedprotocol" json:"framedprotocol"`
	Framedipaddress     *netip.Addr        `db:"framedipaddress" json:"framedipaddress"`
	Framedipv6address   *netip.Addr        `db:"framedipv6address" json:"framedipv6address"`
	Framedipv6prefix    *netip.Addr        `db:"framedipv6prefix" json:"framedipv6prefix"`
	Framedinterfaceid   *string            `db:"framedinterfaceid" json:"framedinterfaceid"`
	Delegatedipv6prefix *netip.Addr        `db:"delegatedipv6prefix" json:"delegatedipv6prefix"`
	Class               *string            `db:"class" json:"class"`
}

type Radcheck struct {
	ID        int64  `db:"id" json:"id"`
	Username  string `db:"username" json:"username"`
	Attribute string `db:"attribute" json:"attribute"`
	Op        string `db:"op" json:"op"`
	Value     string `db:"value" json:"value"`
}

type Radgroupcheck struct {
	ID        int64  `db:"id" json:"id"`
	Groupname string `db:"groupname" json:"groupname"`
	Attribute string `db:"attribute" json:"attribute"`
	Op        string `db:"op" json:"op"`
	Value     string `db:"value" json:"value"`
}

type Radgroupreply struct {
	ID        int64  `db:"id" json:"id"`
	Groupname string `db:"groupname" json:"groupname"`
	Attribute string `db:"attribute" json:"attribute"`
	Op        string `db:"op" json:"op"`
	Value     string `db:"value" json:"value"`
}

type Radpostauth struct {
	ID               int64              `db:"id" json:"id"`
	Username         string             `db:"username" json:"username"`
	Pass             *string            `db:"pass" json:"pass"`
	Reply            *string            `db:"reply" json:"reply"`
	Calledstationid  *string            `db:"calledstationid" json:"calledstationid"`
	Callingstationid *string            `db:"callingstationid" json:"callingstationid"`
	Authdate         pgtype.Timestamptz `db:"authdate" json:"authdate"`
	Class            *string            `db:"class" json:"class"`
}

type Radreply struct {
	ID        int64  `db:"id" json:"id"`
	Username  string `db:"username" json:"username"`
	Attribute string `db:"attribute" json:"attribute"`
	Op        string `db:"op" json:"op"`
	Value     string `db:"value" json:"value"`
}

type Radusergroup struct {
	ID        int64  `db:"id" json:"id"`
	Username  string `db:"username" json:"username"`
	Groupname string `db:"groupname" json:"groupname"`
	Priority  int32  `db:"priority" json:"priority"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Username  string             `db:"username" json:"username"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Groups    []string           `db:"groups" json:"groups"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserPreference struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Timezone  *string            `db:"timezone" json:"timezone"`
	Locale    *string            `db:"locale" json:"locale"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Vlan struct {
	VlanID      int32              `db:"vlan_id" json:"vlan_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
