// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: network_devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNetworkDevice = `-- name: CreateNetworkDevice :one
INSERT INTO network_devices (
  mac_address,
  display_name,
  disabled,
  vlan_id,
  created_by_user_id,
  updated_by_user_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at, disabled
`

type CreateNetworkDeviceParams struct {
	MacAddress      string      `db:"mac_address" json:"mac_address"`
	DisplayName     string      `db:"display_name" json:"display_name"`
	Disabled        bool        `db:"disabled" json:"disabled"`
	VlanID          int32       `db:"vlan_id" json:"vlan_id"`
	CreatedByUserID pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) CreateNetworkDevice(ctx context.Context, arg CreateNetworkDeviceParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, createNetworkDevice,
		arg.MacAddress,
		arg.DisplayName,
		arg.Disabled,
		arg.VlanID,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const deleteNetworkDevice = `-- name: DeleteNetworkDevice :exec
DELETE FROM network_devices
WHERE id = $1
`

type DeleteNetworkDeviceParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteNetworkDevice(ctx context.Context, arg DeleteNetworkDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteNetworkDevice, arg.ID)
	return err
}

const getNetworkDeviceByID = `-- name: GetNetworkDeviceByID :one
SELECT id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at, disabled
FROM network_devices
WHERE id = $1
LIMIT 1
`

type GetNetworkDeviceByIDParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetNetworkDeviceByID(ctx context.Context, arg GetNetworkDeviceByIDParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, getNetworkDeviceByID, arg.ID)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}

const listNetworkDevices = `-- name: ListNetworkDevices :many
SELECT network_devices.id, network_devices.mac_address, network_devices.display_name, network_devices.vlan_id, network_devices.created_by_user_id, network_devices.updated_by_user_id, network_devices.created_at, network_devices.updated_at, network_devices.disabled, vlans.vlan_id, vlans.name, vlans.description, vlans.created_at, vlans.updated_at
FROM network_devices
JOIN vlans ON vlans.vlan_id = network_devices.vlan_id
ORDER BY network_devices.display_name, network_devices.id
`

type ListNetworkDevicesRow struct {
	NetworkDevice NetworkDevice `db:"network_device" json:"network_device"`
	Vlan          Vlan          `db:"vlan" json:"vlan"`
}

func (q *Queries) ListNetworkDevices(ctx context.Context) ([]ListNetworkDevicesRow, error) {
	rows, err := q.db.Query(ctx, listNetworkDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworkDevicesRow{}
	for rows.Next() {
		var i ListNetworkDevicesRow
		if err := rows.Scan(
			&i.NetworkDevice.ID,
			&i.NetworkDevice.MacAddress,
			&i.NetworkDevice.DisplayName,
			&i.NetworkDevice.VlanID,
			&i.NetworkDevice.CreatedByUserID,
			&i.NetworkDevice.UpdatedByUserID,
			&i.NetworkDevice.CreatedAt,
			&i.NetworkDevice.UpdatedAt,
			&i.NetworkDevice.Disabled,
			&i.Vlan.VlanID,
			&i.Vlan.Name,
			&i.Vlan.Description,
			&i.Vlan.CreatedAt,
			&i.Vlan.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNetworkDevice = `-- name: UpdateNetworkDevice :one
UPDATE network_devices
SET
  mac_address = $1,
  display_name = $2,
  disabled = $3,
  vlan_id = $4,
  updated_by_user_id = $5,
  updated_at = NOW()
WHERE id = $6
RETURNING id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at, disabled
`

type UpdateNetworkDeviceParams struct {
	MacAddress      string      `db:"mac_address" json:"mac_address"`
	DisplayName     string      `db:"display_name" json:"display_name"`
	Disabled        bool        `db:"disabled" json:"disabled"`
	VlanID          int32       `db:"vlan_id" json:"vlan_id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
	ID              pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateNetworkDevice(ctx context.Context, arg UpdateNetworkDeviceParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, updateNetworkDevice,
		arg.MacAddress,
		arg.DisplayName,
		arg.Disabled,
		arg.VlanID,
		arg.UpdatedByUserID,
		arg.ID,
	)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
	)
	return i, err
}
