// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNetworkDevices = `-- name: CountNetworkDevices :one
SELECT COUNT(*)
FROM network_devices
`

func (q *Queries) CountNetworkDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNetworkDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNetworkDevice = `-- name: CreateNetworkDevice :one
INSERT INTO network_devices (
  mac_address,
  display_name,
  vlan_id,
  created_by_user_id,
  updated_by_user_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateNetworkDeviceParams struct {
	MacAddress      string      `db:"mac_address" json:"mac_address"`
	DisplayName     string      `db:"display_name" json:"display_name"`
	VlanID          int64       `db:"vlan_id" json:"vlan_id"`
	CreatedByUserID pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
}

func (q *Queries) CreateNetworkDevice(ctx context.Context, arg CreateNetworkDeviceParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, createNetworkDevice,
		arg.MacAddress,
		arg.DisplayName,
		arg.VlanID,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNetworkDevice = `-- name: DeleteNetworkDevice :exec
DELETE FROM network_devices
WHERE id = $1
`

type DeleteNetworkDeviceParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteNetworkDevice(ctx context.Context, arg DeleteNetworkDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteNetworkDevice, arg.ID)
	return err
}

const getNetworkDeviceByID = `-- name: GetNetworkDeviceByID :one
SELECT id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM network_devices
WHERE id = $1
LIMIT 1
`

type GetNetworkDeviceByIDParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetNetworkDeviceByID(ctx context.Context, arg GetNetworkDeviceByIDParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, getNetworkDeviceByID, arg.ID)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNetworkDeviceByMACAddress = `-- name: GetNetworkDeviceByMACAddress :one
SELECT id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM network_devices
WHERE LOWER(mac_address) = LOWER($1)
LIMIT 1
`

type GetNetworkDeviceByMACAddressParams struct {
	MacAddress string `db:"mac_address" json:"mac_address"`
}

func (q *Queries) GetNetworkDeviceByMACAddress(ctx context.Context, arg GetNetworkDeviceByMACAddressParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, getNetworkDeviceByMACAddress, arg.MacAddress)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNetworkDevices = `-- name: ListNetworkDevices :many
SELECT id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM network_devices
ORDER BY display_name, id
`

func (q *Queries) ListNetworkDevices(ctx context.Context) ([]NetworkDevice, error) {
	rows, err := q.db.Query(ctx, listNetworkDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkDevice{}
	for rows.Next() {
		var i NetworkDevice
		if err := rows.Scan(
			&i.ID,
			&i.MacAddress,
			&i.DisplayName,
			&i.VlanID,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNetworkDevice = `-- name: UpdateNetworkDevice :one
UPDATE network_devices
SET
  mac_address = $1,
  display_name = $2,
  vlan_id = $3,
  updated_by_user_id = $4,
  updated_at = NOW()
WHERE id = $5
RETURNING id, mac_address, display_name, vlan_id, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateNetworkDeviceParams struct {
	MacAddress      string      `db:"mac_address" json:"mac_address"`
	DisplayName     string      `db:"display_name" json:"display_name"`
	VlanID          int64       `db:"vlan_id" json:"vlan_id"`
	UpdatedByUserID pgtype.UUID `db:"updated_by_user_id" json:"updated_by_user_id"`
	ID              pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateNetworkDevice(ctx context.Context, arg UpdateNetworkDeviceParams) (NetworkDevice, error) {
	row := q.db.QueryRow(ctx, updateNetworkDevice,
		arg.MacAddress,
		arg.DisplayName,
		arg.VlanID,
		arg.UpdatedByUserID,
		arg.ID,
	)
	var i NetworkDevice
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.DisplayName,
		&i.VlanID,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
