// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presence_catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countObservedPresenceClients = `-- name: CountObservedPresenceClients :one
SELECT COUNT(*)
FROM presence_clients pc
LEFT JOIN network_devices nd ON nd.id = pc.network_device_id
LEFT JOIN presence_observation_points pop ON pop.id = pc.last_observation_point_id
WHERE ($1 = '' OR pc.status = $1)
  AND ($2 = '' OR pc.last_source_type = $2)
  AND ($3 = '' OR pc.last_source_key = $3)
  AND ($4 = '' OR pc.last_medium = $4)
  AND (
    $5 = ''
    OR LOWER(COALESCE(pop.location_label, '')) LIKE '%' || LOWER($5) || '%'
  )
  AND (
    $6 = ''
    OR LOWER(pc.mac_address) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(nd.display_name, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pop.location_label, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pop.display_name, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pop.external_id, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pc.last_ssid, '')) LIKE '%' || LOWER($6) || '%'
  )
`

type CountObservedPresenceClientsParams struct {
	Status        interface{} `db:"status" json:"status"`
	SourceType    interface{} `db:"source_type" json:"source_type"`
	SourceKey     interface{} `db:"source_key" json:"source_key"`
	Medium        interface{} `db:"medium" json:"medium"`
	LocationQuery interface{} `db:"location_query" json:"location_query"`
	Query         interface{} `db:"query" json:"query"`
}

func (q *Queries) CountObservedPresenceClients(ctx context.Context, arg CountObservedPresenceClientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countObservedPresenceClients,
		arg.Status,
		arg.SourceType,
		arg.SourceKey,
		arg.Medium,
		arg.LocationQuery,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPresenceObservationPoints = `-- name: CountPresenceObservationPoints :one
SELECT COUNT(*)
FROM presence_observation_points pop
WHERE ($1 = '' OR pop.source_type = $1)
  AND ($2 = '' OR pop.source_key = $2)
  AND ($3 = '' OR pop.medium = $3)
  AND (
    $4 = ''
    OR LOWER(pop.external_id) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.parent_external_id) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.display_name) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.location_label) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.notes) LIKE '%' || LOWER($4) || '%'
    OR LOWER(COALESCE(pop.ssid, '')) LIKE '%' || LOWER($4) || '%'
  )
`

type CountPresenceObservationPointsParams struct {
	SourceType interface{} `db:"source_type" json:"source_type"`
	SourceKey  interface{} `db:"source_key" json:"source_key"`
	Medium     interface{} `db:"medium" json:"medium"`
	Query      interface{} `db:"query" json:"query"`
}

func (q *Queries) CountPresenceObservationPoints(ctx context.Context, arg CountPresenceObservationPointsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPresenceObservationPoints,
		arg.SourceType,
		arg.SourceKey,
		arg.Medium,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getManagedPresenceClientByDeviceID = `-- name: GetManagedPresenceClientByDeviceID :one
SELECT
  pc.id, pc.mac_address, pc.network_device_id, pc.status, pc.first_seen_at, pc.last_seen_at, pc.last_source_key, pc.last_source_type, pc.last_medium, pc.last_observation_point_id, pc.last_ssid, pc.last_metadata, pc.created_at, pc.updated_at,
  COALESCE(pop.external_id, '') AS observation_external_id,
  COALESCE(pop.display_name, '') AS observation_display_name,
  COALESCE(pop.location_label, '') AS observation_location_label
FROM presence_clients pc
LEFT JOIN presence_observation_points pop ON pop.id = pc.last_observation_point_id
WHERE pc.network_device_id = $1
ORDER BY pc.last_seen_at DESC
LIMIT 1
`

type GetManagedPresenceClientByDeviceIDParams struct {
	NetworkDeviceID pgtype.UUID `db:"network_device_id" json:"network_device_id"`
}

type GetManagedPresenceClientByDeviceIDRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	MacAddress               string             `db:"mac_address" json:"mac_address"`
	NetworkDeviceID          pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	Status                   string             `db:"status" json:"status"`
	FirstSeenAt              pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt               pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	LastSourceKey            string             `db:"last_source_key" json:"last_source_key"`
	LastSourceType           string             `db:"last_source_type" json:"last_source_type"`
	LastMedium               string             `db:"last_medium" json:"last_medium"`
	LastObservationPointID   pgtype.UUID        `db:"last_observation_point_id" json:"last_observation_point_id"`
	LastSsid                 *string            `db:"last_ssid" json:"last_ssid"`
	LastMetadata             []byte             `db:"last_metadata" json:"last_metadata"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ObservationExternalID    string             `db:"observation_external_id" json:"observation_external_id"`
	ObservationDisplayName   string             `db:"observation_display_name" json:"observation_display_name"`
	ObservationLocationLabel string             `db:"observation_location_label" json:"observation_location_label"`
}

func (q *Queries) GetManagedPresenceClientByDeviceID(ctx context.Context, arg GetManagedPresenceClientByDeviceIDParams) (GetManagedPresenceClientByDeviceIDRow, error) {
	row := q.db.QueryRow(ctx, getManagedPresenceClientByDeviceID, arg.NetworkDeviceID)
	var i GetManagedPresenceClientByDeviceIDRow
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.NetworkDeviceID,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSourceKey,
		&i.LastSourceType,
		&i.LastMedium,
		&i.LastObservationPointID,
		&i.LastSsid,
		&i.LastMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservationExternalID,
		&i.ObservationDisplayName,
		&i.ObservationLocationLabel,
	)
	return i, err
}

const getPresenceObservationPointByID = `-- name: GetPresenceObservationPointByID :one
SELECT id, source_key, source_type, medium, external_id, parent_external_id, display_name, location_label, notes, ssid, metadata, last_seen_at, created_at, updated_at
FROM presence_observation_points
WHERE id = $1
LIMIT 1
`

type GetPresenceObservationPointByIDParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetPresenceObservationPointByID(ctx context.Context, arg GetPresenceObservationPointByIDParams) (PresenceObservationPoint, error) {
	row := q.db.QueryRow(ctx, getPresenceObservationPointByID, arg.ID)
	var i PresenceObservationPoint
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.SourceType,
		&i.Medium,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.DisplayName,
		&i.LocationLabel,
		&i.Notes,
		&i.Ssid,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagedPresenceClients = `-- name: ListManagedPresenceClients :many
SELECT
  pc.id, pc.mac_address, pc.network_device_id, pc.status, pc.first_seen_at, pc.last_seen_at, pc.last_source_key, pc.last_source_type, pc.last_medium, pc.last_observation_point_id, pc.last_ssid, pc.last_metadata, pc.created_at, pc.updated_at,
  COALESCE(pop.external_id, '') AS observation_external_id,
  COALESCE(pop.display_name, '') AS observation_display_name,
  COALESCE(pop.location_label, '') AS observation_location_label
FROM presence_clients pc
LEFT JOIN presence_observation_points pop ON pop.id = pc.last_observation_point_id
WHERE pc.network_device_id IS NOT NULL
ORDER BY pc.last_seen_at DESC
`

type ListManagedPresenceClientsRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	MacAddress               string             `db:"mac_address" json:"mac_address"`
	NetworkDeviceID          pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	Status                   string             `db:"status" json:"status"`
	FirstSeenAt              pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt               pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	LastSourceKey            string             `db:"last_source_key" json:"last_source_key"`
	LastSourceType           string             `db:"last_source_type" json:"last_source_type"`
	LastMedium               string             `db:"last_medium" json:"last_medium"`
	LastObservationPointID   pgtype.UUID        `db:"last_observation_point_id" json:"last_observation_point_id"`
	LastSsid                 *string            `db:"last_ssid" json:"last_ssid"`
	LastMetadata             []byte             `db:"last_metadata" json:"last_metadata"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ObservationExternalID    string             `db:"observation_external_id" json:"observation_external_id"`
	ObservationDisplayName   string             `db:"observation_display_name" json:"observation_display_name"`
	ObservationLocationLabel string             `db:"observation_location_label" json:"observation_location_label"`
}

func (q *Queries) ListManagedPresenceClients(ctx context.Context) ([]ListManagedPresenceClientsRow, error) {
	rows, err := q.db.Query(ctx, listManagedPresenceClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedPresenceClientsRow{}
	for rows.Next() {
		var i ListManagedPresenceClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.MacAddress,
			&i.NetworkDeviceID,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastSourceKey,
			&i.LastSourceType,
			&i.LastMedium,
			&i.LastObservationPointID,
			&i.LastSsid,
			&i.LastMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservationExternalID,
			&i.ObservationDisplayName,
			&i.ObservationLocationLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservedPresenceClients = `-- name: ListObservedPresenceClients :many
SELECT
  pc.id, pc.mac_address, pc.network_device_id, pc.status, pc.first_seen_at, pc.last_seen_at, pc.last_source_key, pc.last_source_type, pc.last_medium, pc.last_observation_point_id, pc.last_ssid, pc.last_metadata, pc.created_at, pc.updated_at,
  COALESCE(nd.display_name, '') AS managed_device_display_name,
  COALESCE(pop.external_id, '') AS observation_external_id,
  COALESCE(pop.display_name, '') AS observation_display_name,
  COALESCE(pop.location_label, '') AS observation_location_label
FROM presence_clients pc
LEFT JOIN network_devices nd ON nd.id = pc.network_device_id
LEFT JOIN presence_observation_points pop ON pop.id = pc.last_observation_point_id
WHERE ($1 = '' OR pc.status = $1)
  AND ($2 = '' OR pc.last_source_type = $2)
  AND ($3 = '' OR pc.last_source_key = $3)
  AND ($4 = '' OR pc.last_medium = $4)
  AND (
    $5 = ''
    OR LOWER(COALESCE(pop.location_label, '')) LIKE '%' || LOWER($5) || '%'
  )
  AND (
    $6 = ''
    OR LOWER(pc.mac_address) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(nd.display_name, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pop.location_label, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pop.display_name, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pop.external_id, '')) LIKE '%' || LOWER($6) || '%'
    OR LOWER(COALESCE(pc.last_ssid, '')) LIKE '%' || LOWER($6) || '%'
  )
ORDER BY
  CASE WHEN pc.status = 'online' THEN 0 ELSE 1 END,
  pc.last_seen_at DESC,
  pc.mac_address
LIMIT $8
OFFSET $7
`

type ListObservedPresenceClientsParams struct {
	Status        interface{} `db:"status" json:"status"`
	SourceType    interface{} `db:"source_type" json:"source_type"`
	SourceKey     interface{} `db:"source_key" json:"source_key"`
	Medium        interface{} `db:"medium" json:"medium"`
	LocationQuery interface{} `db:"location_query" json:"location_query"`
	Query         interface{} `db:"query" json:"query"`
	OffsetCount   int32       `db:"offset_count" json:"offset_count"`
	LimitCount    int32       `db:"limit_count" json:"limit_count"`
}

type ListObservedPresenceClientsRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	MacAddress               string             `db:"mac_address" json:"mac_address"`
	NetworkDeviceID          pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	Status                   string             `db:"status" json:"status"`
	FirstSeenAt              pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt               pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	LastSourceKey            string             `db:"last_source_key" json:"last_source_key"`
	LastSourceType           string             `db:"last_source_type" json:"last_source_type"`
	LastMedium               string             `db:"last_medium" json:"last_medium"`
	LastObservationPointID   pgtype.UUID        `db:"last_observation_point_id" json:"last_observation_point_id"`
	LastSsid                 *string            `db:"last_ssid" json:"last_ssid"`
	LastMetadata             []byte             `db:"last_metadata" json:"last_metadata"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ManagedDeviceDisplayName string             `db:"managed_device_display_name" json:"managed_device_display_name"`
	ObservationExternalID    string             `db:"observation_external_id" json:"observation_external_id"`
	ObservationDisplayName   string             `db:"observation_display_name" json:"observation_display_name"`
	ObservationLocationLabel string             `db:"observation_location_label" json:"observation_location_label"`
}

func (q *Queries) ListObservedPresenceClients(ctx context.Context, arg ListObservedPresenceClientsParams) ([]ListObservedPresenceClientsRow, error) {
	rows, err := q.db.Query(ctx, listObservedPresenceClients,
		arg.Status,
		arg.SourceType,
		arg.SourceKey,
		arg.Medium,
		arg.LocationQuery,
		arg.Query,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservedPresenceClientsRow{}
	for rows.Next() {
		var i ListObservedPresenceClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.MacAddress,
			&i.NetworkDeviceID,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastSourceKey,
			&i.LastSourceType,
			&i.LastMedium,
			&i.LastObservationPointID,
			&i.LastSsid,
			&i.LastMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManagedDeviceDisplayName,
			&i.ObservationExternalID,
			&i.ObservationDisplayName,
			&i.ObservationLocationLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresenceObservationPoints = `-- name: ListPresenceObservationPoints :many
SELECT id, source_key, source_type, medium, external_id, parent_external_id, display_name, location_label, notes, ssid, metadata, last_seen_at, created_at, updated_at
FROM presence_observation_points pop
WHERE ($1 = '' OR pop.source_type = $1)
  AND ($2 = '' OR pop.source_key = $2)
  AND ($3 = '' OR pop.medium = $3)
  AND (
    $4 = ''
    OR LOWER(pop.external_id) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.parent_external_id) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.display_name) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.location_label) LIKE '%' || LOWER($4) || '%'
    OR LOWER(pop.notes) LIKE '%' || LOWER($4) || '%'
    OR LOWER(COALESCE(pop.ssid, '')) LIKE '%' || LOWER($4) || '%'
  )
ORDER BY pop.medium, pop.source_key, pop.external_id
LIMIT $6
OFFSET $5
`

type ListPresenceObservationPointsParams struct {
	SourceType  interface{} `db:"source_type" json:"source_type"`
	SourceKey   interface{} `db:"source_key" json:"source_key"`
	Medium      interface{} `db:"medium" json:"medium"`
	Query       interface{} `db:"query" json:"query"`
	OffsetCount int32       `db:"offset_count" json:"offset_count"`
	LimitCount  int32       `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListPresenceObservationPoints(ctx context.Context, arg ListPresenceObservationPointsParams) ([]PresenceObservationPoint, error) {
	rows, err := q.db.Query(ctx, listPresenceObservationPoints,
		arg.SourceType,
		arg.SourceKey,
		arg.Medium,
		arg.Query,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresenceObservationPoint{}
	for rows.Next() {
		var i PresenceObservationPoint
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.SourceType,
			&i.Medium,
			&i.ExternalID,
			&i.ParentExternalID,
			&i.DisplayName,
			&i.LocationLabel,
			&i.Notes,
			&i.Ssid,
			&i.Metadata,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePresenceObservationPointAdmin = `-- name: UpdatePresenceObservationPointAdmin :one
UPDATE presence_observation_points
SET
  location_label = $1,
  notes = $2
WHERE id = $3
RETURNING id, source_key, source_type, medium, external_id, parent_external_id, display_name, location_label, notes, ssid, metadata, last_seen_at, created_at, updated_at
`

type UpdatePresenceObservationPointAdminParams struct {
	LocationLabel string      `db:"location_label" json:"location_label"`
	Notes         string      `db:"notes" json:"notes"`
	ID            pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdatePresenceObservationPointAdmin(ctx context.Context, arg UpdatePresenceObservationPointAdminParams) (PresenceObservationPoint, error) {
	row := q.db.QueryRow(ctx, updatePresenceObservationPointAdmin, arg.LocationLabel, arg.Notes, arg.ID)
	var i PresenceObservationPoint
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.SourceType,
		&i.Medium,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.DisplayName,
		&i.LocationLabel,
		&i.Notes,
		&i.Ssid,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
