// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presence.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPresenceWorkerState = `-- name: GetPresenceWorkerState :one
SELECT worker_name, source_key, state, last_polled_at, last_succeeded_at, created_at, updated_at
FROM presence_worker_state
WHERE worker_name = $1
  AND source_key = $2
LIMIT 1
`

type GetPresenceWorkerStateParams struct {
	WorkerName string `db:"worker_name" json:"worker_name"`
	SourceKey  string `db:"source_key" json:"source_key"`
}

func (q *Queries) GetPresenceWorkerState(ctx context.Context, arg GetPresenceWorkerStateParams) (PresenceWorkerState, error) {
	row := q.db.QueryRow(ctx, getPresenceWorkerState, arg.WorkerName, arg.SourceKey)
	var i PresenceWorkerState
	err := row.Scan(
		&i.WorkerName,
		&i.SourceKey,
		&i.State,
		&i.LastPolledAt,
		&i.LastSucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPresenceClient = `-- name: UpsertPresenceClient :one
INSERT INTO presence_clients (
  mac_address,
  network_device_id,
  status,
  first_seen_at,
  last_seen_at,
  last_source_key,
  last_source_type,
  last_medium,
  last_observation_point_id,
  last_ssid,
  last_metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
ON CONFLICT (LOWER(mac_address)) DO UPDATE SET
  network_device_id = COALESCE(EXCLUDED.network_device_id, presence_clients.network_device_id),
  status = CASE
    WHEN EXCLUDED.last_seen_at >= presence_clients.last_seen_at THEN EXCLUDED.status
    ELSE presence_clients.status
  END,
  first_seen_at = LEAST(presence_clients.first_seen_at, EXCLUDED.first_seen_at),
  last_seen_at = GREATEST(presence_clients.last_seen_at, EXCLUDED.last_seen_at),
  last_source_key = CASE
    WHEN EXCLUDED.last_seen_at >= presence_clients.last_seen_at THEN EXCLUDED.last_source_key
    ELSE presence_clients.last_source_key
  END,
  last_source_type = CASE
    WHEN EXCLUDED.last_seen_at >= presence_clients.last_seen_at THEN EXCLUDED.last_source_type
    ELSE presence_clients.last_source_type
  END,
  last_medium = CASE
    WHEN EXCLUDED.last_seen_at >= presence_clients.last_seen_at THEN EXCLUDED.last_medium
    ELSE presence_clients.last_medium
  END,
  last_observation_point_id = CASE
    WHEN EXCLUDED.last_seen_at >= presence_clients.last_seen_at AND EXCLUDED.last_observation_point_id IS NOT NULL THEN EXCLUDED.last_observation_point_id
    ELSE presence_clients.last_observation_point_id
  END,
  last_ssid = CASE
    WHEN EXCLUDED.last_seen_at >= presence_clients.last_seen_at AND EXCLUDED.last_ssid IS NOT NULL THEN EXCLUDED.last_ssid
    ELSE presence_clients.last_ssid
  END,
  last_metadata = presence_clients.last_metadata || EXCLUDED.last_metadata
RETURNING id, mac_address, network_device_id, status, first_seen_at, last_seen_at, last_source_key, last_source_type, last_medium, last_observation_point_id, last_ssid, last_metadata, created_at, updated_at
`

type UpsertPresenceClientParams struct {
	MacAddress             string             `db:"mac_address" json:"mac_address"`
	NetworkDeviceID        pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	Status                 string             `db:"status" json:"status"`
	FirstSeenAt            pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt             pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	LastSourceKey          string             `db:"last_source_key" json:"last_source_key"`
	LastSourceType         string             `db:"last_source_type" json:"last_source_type"`
	LastMedium             string             `db:"last_medium" json:"last_medium"`
	LastObservationPointID pgtype.UUID        `db:"last_observation_point_id" json:"last_observation_point_id"`
	LastSsid               *string            `db:"last_ssid" json:"last_ssid"`
	LastMetadata           []byte             `db:"last_metadata" json:"last_metadata"`
}

func (q *Queries) UpsertPresenceClient(ctx context.Context, arg UpsertPresenceClientParams) (PresenceClient, error) {
	row := q.db.QueryRow(ctx, upsertPresenceClient,
		arg.MacAddress,
		arg.NetworkDeviceID,
		arg.Status,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.LastSourceKey,
		arg.LastSourceType,
		arg.LastMedium,
		arg.LastObservationPointID,
		arg.LastSsid,
		arg.LastMetadata,
	)
	var i PresenceClient
	err := row.Scan(
		&i.ID,
		&i.MacAddress,
		&i.NetworkDeviceID,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSourceKey,
		&i.LastSourceType,
		&i.LastMedium,
		&i.LastObservationPointID,
		&i.LastSsid,
		&i.LastMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPresenceObservationPoint = `-- name: UpsertPresenceObservationPoint :one
INSERT INTO presence_observation_points (
  source_key,
  source_type,
  medium,
  external_id,
  parent_external_id,
  display_name,
  ssid,
  metadata,
  last_seen_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (source_key, LOWER(external_id)) DO UPDATE SET
  source_type = EXCLUDED.source_type,
  medium = EXCLUDED.medium,
  parent_external_id = CASE
    WHEN EXCLUDED.parent_external_id <> '' THEN EXCLUDED.parent_external_id
    ELSE presence_observation_points.parent_external_id
  END,
  display_name = CASE
    WHEN EXCLUDED.display_name <> '' THEN EXCLUDED.display_name
    ELSE presence_observation_points.display_name
  END,
  ssid = COALESCE(EXCLUDED.ssid, presence_observation_points.ssid),
  metadata = presence_observation_points.metadata || EXCLUDED.metadata,
  last_seen_at = CASE
    WHEN presence_observation_points.last_seen_at IS NULL THEN EXCLUDED.last_seen_at
    WHEN EXCLUDED.last_seen_at IS NULL THEN presence_observation_points.last_seen_at
    WHEN EXCLUDED.last_seen_at > presence_observation_points.last_seen_at THEN EXCLUDED.last_seen_at
    ELSE presence_observation_points.last_seen_at
  END
RETURNING id, source_key, source_type, medium, external_id, parent_external_id, display_name, location_label, notes, ssid, metadata, last_seen_at, created_at, updated_at
`

type UpsertPresenceObservationPointParams struct {
	SourceKey        string             `db:"source_key" json:"source_key"`
	SourceType       string             `db:"source_type" json:"source_type"`
	Medium           string             `db:"medium" json:"medium"`
	ExternalID       string             `db:"external_id" json:"external_id"`
	ParentExternalID string             `db:"parent_external_id" json:"parent_external_id"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	Ssid             *string            `db:"ssid" json:"ssid"`
	Metadata         []byte             `db:"metadata" json:"metadata"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) UpsertPresenceObservationPoint(ctx context.Context, arg UpsertPresenceObservationPointParams) (PresenceObservationPoint, error) {
	row := q.db.QueryRow(ctx, upsertPresenceObservationPoint,
		arg.SourceKey,
		arg.SourceType,
		arg.Medium,
		arg.ExternalID,
		arg.ParentExternalID,
		arg.DisplayName,
		arg.Ssid,
		arg.Metadata,
		arg.LastSeenAt,
	)
	var i PresenceObservationPoint
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.SourceType,
		&i.Medium,
		&i.ExternalID,
		&i.ParentExternalID,
		&i.DisplayName,
		&i.LocationLabel,
		&i.Notes,
		&i.Ssid,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPresenceSession = `-- name: UpsertPresenceSession :one
INSERT INTO presence_sessions (
  source_key,
  source_type,
  medium,
  source_session_key,
  client_mac_address,
  network_device_id,
  observation_point_id,
  started_at,
  source_updated_at,
  last_seen_at,
  ended_at,
  ssid,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13
)
ON CONFLICT (source_key, source_session_key) DO UPDATE SET
  network_device_id = COALESCE(EXCLUDED.network_device_id, presence_sessions.network_device_id),
  observation_point_id = COALESCE(EXCLUDED.observation_point_id, presence_sessions.observation_point_id),
  started_at = LEAST(presence_sessions.started_at, EXCLUDED.started_at),
  source_updated_at = GREATEST(presence_sessions.source_updated_at, EXCLUDED.source_updated_at),
  last_seen_at = GREATEST(presence_sessions.last_seen_at, EXCLUDED.last_seen_at),
  ended_at = CASE
    WHEN presence_sessions.ended_at IS NULL THEN EXCLUDED.ended_at
    WHEN EXCLUDED.ended_at IS NULL THEN presence_sessions.ended_at
    WHEN EXCLUDED.ended_at > presence_sessions.ended_at THEN EXCLUDED.ended_at
    ELSE presence_sessions.ended_at
  END,
  ssid = COALESCE(EXCLUDED.ssid, presence_sessions.ssid),
  metadata = presence_sessions.metadata || EXCLUDED.metadata
RETURNING id, source_key, source_type, medium, source_session_key, client_mac_address, network_device_id, observation_point_id, started_at, source_updated_at, last_seen_at, ended_at, ssid, metadata, created_at, updated_at
`

type UpsertPresenceSessionParams struct {
	SourceKey          string             `db:"source_key" json:"source_key"`
	SourceType         string             `db:"source_type" json:"source_type"`
	Medium             string             `db:"medium" json:"medium"`
	SourceSessionKey   string             `db:"source_session_key" json:"source_session_key"`
	ClientMacAddress   string             `db:"client_mac_address" json:"client_mac_address"`
	NetworkDeviceID    pgtype.UUID        `db:"network_device_id" json:"network_device_id"`
	ObservationPointID pgtype.UUID        `db:"observation_point_id" json:"observation_point_id"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	SourceUpdatedAt    pgtype.Timestamptz `db:"source_updated_at" json:"source_updated_at"`
	LastSeenAt         pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	EndedAt            pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	Ssid               *string            `db:"ssid" json:"ssid"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertPresenceSession(ctx context.Context, arg UpsertPresenceSessionParams) (PresenceSession, error) {
	row := q.db.QueryRow(ctx, upsertPresenceSession,
		arg.SourceKey,
		arg.SourceType,
		arg.Medium,
		arg.SourceSessionKey,
		arg.ClientMacAddress,
		arg.NetworkDeviceID,
		arg.ObservationPointID,
		arg.StartedAt,
		arg.SourceUpdatedAt,
		arg.LastSeenAt,
		arg.EndedAt,
		arg.Ssid,
		arg.Metadata,
	)
	var i PresenceSession
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.SourceType,
		&i.Medium,
		&i.SourceSessionKey,
		&i.ClientMacAddress,
		&i.NetworkDeviceID,
		&i.ObservationPointID,
		&i.StartedAt,
		&i.SourceUpdatedAt,
		&i.LastSeenAt,
		&i.EndedAt,
		&i.Ssid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPresenceWorkerState = `-- name: UpsertPresenceWorkerState :one
INSERT INTO presence_worker_state (
  worker_name,
  source_key,
  state,
  last_polled_at,
  last_succeeded_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (worker_name, source_key) DO UPDATE SET
  state = EXCLUDED.state,
  last_polled_at = EXCLUDED.last_polled_at,
  last_succeeded_at = EXCLUDED.last_succeeded_at
RETURNING worker_name, source_key, state, last_polled_at, last_succeeded_at, created_at, updated_at
`

type UpsertPresenceWorkerStateParams struct {
	WorkerName      string             `db:"worker_name" json:"worker_name"`
	SourceKey       string             `db:"source_key" json:"source_key"`
	State           []byte             `db:"state" json:"state"`
	LastPolledAt    pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	LastSucceededAt pgtype.Timestamptz `db:"last_succeeded_at" json:"last_succeeded_at"`
}

func (q *Queries) UpsertPresenceWorkerState(ctx context.Context, arg UpsertPresenceWorkerStateParams) (PresenceWorkerState, error) {
	row := q.db.QueryRow(ctx, upsertPresenceWorkerState,
		arg.WorkerName,
		arg.SourceKey,
		arg.State,
		arg.LastPolledAt,
		arg.LastSucceededAt,
	)
	var i PresenceWorkerState
	err := row.Scan(
		&i.WorkerName,
		&i.SourceKey,
		&i.State,
		&i.LastPolledAt,
		&i.LastSucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
