// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountActiveAuthSessions(ctx context.Context) (int64, error)
	CountActiveAuthSessionsByUserID(ctx context.Context, arg CountActiveAuthSessionsByUserIDParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountNetworkDevices(ctx context.Context) (int64, error)
	CountVlans(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthDeviceAuthorization(ctx context.Context, arg CreateAuthDeviceAuthorizationParams) (AuthDeviceAuthorization, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateNetworkDevice(ctx context.Context, arg CreateNetworkDeviceParams) (NetworkDevice, error)
	CreateVlan(ctx context.Context, arg CreateVlanParams) (Vlan, error)
	DeleteNetworkDevice(ctx context.Context, arg DeleteNetworkDeviceParams) error
	DeleteRadcheckCleartextPasswordByUsername(ctx context.Context, arg DeleteRadcheckCleartextPasswordByUsernameParams) error
	DeleteRadgrouprepliesByGroupname(ctx context.Context, arg DeleteRadgrouprepliesByGroupnameParams) error
	DeleteRadusergroupsByUsername(ctx context.Context, arg DeleteRadusergroupsByUsernameParams) error
	DeleteVlan(ctx context.Context, arg DeleteVlanParams) error
	GetAuthDeviceAuthorizationByDeviceCode(ctx context.Context, arg GetAuthDeviceAuthorizationByDeviceCodeParams) (AuthDeviceAuthorization, error)
	GetAuthDeviceAuthorizationByUserCode(ctx context.Context, arg GetAuthDeviceAuthorizationByUserCodeParams) (AuthDeviceAuthorization, error)
	GetAuthSessionByID(ctx context.Context, arg GetAuthSessionByIDParams) (AuthSession, error)
	GetAuthSessionByRefreshTokenHash(ctx context.Context, arg GetAuthSessionByRefreshTokenHashParams) (AuthSession, error)
	GetNetworkDeviceByID(ctx context.Context, arg GetNetworkDeviceByIDParams) (NetworkDevice, error)
	GetNetworkDeviceByMACAddress(ctx context.Context, arg GetNetworkDeviceByMACAddressParams) (NetworkDevice, error)
	GetPresenceWorkerState(ctx context.Context, arg GetPresenceWorkerStateParams) (PresenceWorkerState, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error)
	GetVlanByName(ctx context.Context, arg GetVlanByNameParams) (Vlan, error)
	GetVlanByVlanID(ctx context.Context, arg GetVlanByVlanIDParams) (Vlan, error)
	InsertRadgroupreply(ctx context.Context, arg InsertRadgroupreplyParams) error
	InsertRadusergroup(ctx context.Context, arg InsertRadusergroupParams) error
	ListActiveAuthSessionsByUserPage(ctx context.Context, arg ListActiveAuthSessionsByUserPageParams) ([]AuthSession, error)
	ListActiveAuthSessionsPage(ctx context.Context, arg ListActiveAuthSessionsPageParams) ([]AuthSession, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuthSessions(ctx context.Context) ([]AuthSession, error)
	ListAuthSessionsByUserID(ctx context.Context, arg ListAuthSessionsByUserIDParams) ([]AuthSession, error)
	ListNetworkDevices(ctx context.Context) ([]NetworkDevice, error)
	ListRadacctRowsAfterID(ctx context.Context, arg ListRadacctRowsAfterIDParams) ([]Radacct, error)
	ListVlans(ctx context.Context) ([]Vlan, error)
	RevokeAllActiveAuthSessions(ctx context.Context, arg RevokeAllActiveAuthSessionsParams) (int64, error)
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (AuthSession, error)
	RevokeAuthSessionFamily(ctx context.Context, arg RevokeAuthSessionFamilyParams) (int64, error)
	RevokeOtherAuthSessionsForUser(ctx context.Context, arg RevokeOtherAuthSessionsForUserParams) (int64, error)
	TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) (AuthSession, error)
	UpdateAuthDeviceAuthorizationStatus(ctx context.Context, arg UpdateAuthDeviceAuthorizationStatusParams) (AuthDeviceAuthorization, error)
	UpdateNetworkDevice(ctx context.Context, arg UpdateNetworkDeviceParams) (NetworkDevice, error)
	UpdateRadusergroupsGroupname(ctx context.Context, arg UpdateRadusergroupsGroupnameParams) error
	UpdateVlan(ctx context.Context, arg UpdateVlanParams) (Vlan, error)
	UpsertPresenceClient(ctx context.Context, arg UpsertPresenceClientParams) (PresenceClient, error)
	UpsertPresenceObservationPoint(ctx context.Context, arg UpsertPresenceObservationPointParams) (PresenceObservationPoint, error)
	UpsertPresenceSession(ctx context.Context, arg UpsertPresenceSessionParams) (PresenceSession, error)
	UpsertPresenceWorkerState(ctx context.Context, arg UpsertPresenceWorkerStateParams) (PresenceWorkerState, error)
	UpsertRadcheckCleartextPassword(ctx context.Context, arg UpsertRadcheckCleartextPasswordParams) error
	UpsertUserByUsername(ctx context.Context, arg UpsertUserByUsernameParams) (User, error)
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
