// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: radacct_presence.sql

package db

import (
	"context"
)

const listRadacctRowsAfterID = `-- name: ListRadacctRowsAfterID :many
SELECT radacctid, acctsessionid, acctuniqueid, username, groupname, realm, nasipaddress, nasportid, nasporttype, acctstarttime, acctupdatetime, acctstoptime, acctinterval, acctsessiontime, acctauthentic, connectinfo_start, connectinfo_stop, acctinputoctets, acctoutputoctets, calledstationid, callingstationid, acctterminatecause, servicetype, framedprotocol, framedipaddress, framedipv6address, framedipv6prefix, framedinterfaceid, delegatedipv6prefix, class
FROM radacct
WHERE radacctid > $1
ORDER BY radacctid ASC
LIMIT $2
`

type ListRadacctRowsAfterIDParams struct {
	AfterRadacctID int64 `db:"after_radacct_id" json:"after_radacct_id"`
	LimitCount     int32 `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListRadacctRowsAfterID(ctx context.Context, arg ListRadacctRowsAfterIDParams) ([]Radacct, error) {
	rows, err := q.db.Query(ctx, listRadacctRowsAfterID, arg.AfterRadacctID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Radacct{}
	for rows.Next() {
		var i Radacct
		if err := rows.Scan(
			&i.Radacctid,
			&i.Acctsessionid,
			&i.Acctuniqueid,
			&i.Username,
			&i.Groupname,
			&i.Realm,
			&i.Nasipaddress,
			&i.Nasportid,
			&i.Nasporttype,
			&i.Acctstarttime,
			&i.Acctupdatetime,
			&i.Acctstoptime,
			&i.Acctinterval,
			&i.Acctsessiontime,
			&i.Acctauthentic,
			&i.ConnectinfoStart,
			&i.ConnectinfoStop,
			&i.Acctinputoctets,
			&i.Acctoutputoctets,
			&i.Calledstationid,
			&i.Callingstationid,
			&i.Acctterminatecause,
			&i.Servicetype,
			&i.Framedprotocol,
			&i.Framedipaddress,
			&i.Framedipv6address,
			&i.Framedipv6prefix,
			&i.Framedinterfaceid,
			&i.Delegatedipv6prefix,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
