// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: radius_network_devices.sql

package db

import (
	"context"
)

const deleteRadcheckCleartextPasswordByUsername = `-- name: DeleteRadcheckCleartextPasswordByUsername :exec
DELETE FROM radcheck
WHERE username = $1
  AND attribute = 'Cleartext-Password'
`

type DeleteRadcheckCleartextPasswordByUsernameParams struct {
	Username string `db:"username" json:"username"`
}

func (q *Queries) DeleteRadcheckCleartextPasswordByUsername(ctx context.Context, arg DeleteRadcheckCleartextPasswordByUsernameParams) error {
	_, err := q.db.Exec(ctx, deleteRadcheckCleartextPasswordByUsername, arg.Username)
	return err
}

const deleteRadusergroupsByUsername = `-- name: DeleteRadusergroupsByUsername :exec
DELETE FROM radusergroup
WHERE username = $1
`

type DeleteRadusergroupsByUsernameParams struct {
	Username string `db:"username" json:"username"`
}

func (q *Queries) DeleteRadusergroupsByUsername(ctx context.Context, arg DeleteRadusergroupsByUsernameParams) error {
	_, err := q.db.Exec(ctx, deleteRadusergroupsByUsername, arg.Username)
	return err
}

const insertRadusergroup = `-- name: InsertRadusergroup :exec
INSERT INTO radusergroup (
  username,
  groupname,
  priority
) VALUES (
  $1,
  $2,
  $3
)
`

type InsertRadusergroupParams struct {
	Username  string `db:"username" json:"username"`
	Groupname string `db:"groupname" json:"groupname"`
	Priority  int32  `db:"priority" json:"priority"`
}

func (q *Queries) InsertRadusergroup(ctx context.Context, arg InsertRadusergroupParams) error {
	_, err := q.db.Exec(ctx, insertRadusergroup, arg.Username, arg.Groupname, arg.Priority)
	return err
}

const upsertRadcheckCleartextPassword = `-- name: UpsertRadcheckCleartextPassword :exec
INSERT INTO radcheck (
  username,
  attribute,
  op,
  value
) VALUES (
  $1,
  'Cleartext-Password',
  ':=',
  $2
)
ON CONFLICT (username, attribute) DO UPDATE SET
  op = EXCLUDED.op,
  value = EXCLUDED.value
`

type UpsertRadcheckCleartextPasswordParams struct {
	Username string `db:"username" json:"username"`
	Value    string `db:"value" json:"value"`
}

func (q *Queries) UpsertRadcheckCleartextPassword(ctx context.Context, arg UpsertRadcheckCleartextPasswordParams) error {
	_, err := q.db.Exec(ctx, upsertRadcheckCleartextPassword, arg.Username, arg.Value)
	return err
}
