// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, name, email, groups, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Groups,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, name, email, groups, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

type GetUserByUsernameParams struct {
	Username string `db:"username" json:"username"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Groups,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByUsername = `-- name: UpsertUserByUsername :one
INSERT INTO users (
  username,
  name,
  email,
  groups
) VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (username) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  groups = EXCLUDED.groups,
  updated_at = NOW()
RETURNING id, username, name, email, groups, created_at, updated_at
`

type UpsertUserByUsernameParams struct {
	Username string   `db:"username" json:"username"`
	Name     string   `db:"name" json:"name"`
	Email    string   `db:"email" json:"email"`
	Groups   []string `db:"groups" json:"groups"`
}

func (q *Queries) UpsertUserByUsername(ctx context.Context, arg UpsertUserByUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByUsername,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.Groups,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.Groups,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
