// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (
  user_id,
  timezone,
  locale
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (user_id) DO UPDATE SET
  timezone = EXCLUDED.timezone,
  locale = EXCLUDED.locale,
  updated_at = NOW()
RETURNING user_id, timezone, locale, created_at, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Timezone *string     `db:"timezone" json:"timezone"`
	Locale   *string     `db:"locale" json:"locale"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences, arg.UserID, arg.Timezone, arg.Locale)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
