// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vlans.sql

package db

import (
	"context"
)

const countVlans = `-- name: CountVlans :one
SELECT COUNT(*)
FROM vlans
`

func (q *Queries) CountVlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVlan = `-- name: CreateVlan :one
INSERT INTO vlans (
  name,
  vlan_id,
  description,
  is_active
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, name, vlan_id, description, is_active, created_at, updated_at
`

type CreateVlanParams struct {
	Name        string `db:"name" json:"name"`
	VlanID      int32  `db:"vlan_id" json:"vlan_id"`
	Description string `db:"description" json:"description"`
	IsActive    bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateVlan(ctx context.Context, arg CreateVlanParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, createVlan,
		arg.Name,
		arg.VlanID,
		arg.Description,
		arg.IsActive,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VlanID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVlan = `-- name: DeleteVlan :exec
DELETE FROM vlans
WHERE id = $1
`

type DeleteVlanParams struct {
	ID int64 `db:"id" json:"id"`
}

func (q *Queries) DeleteVlan(ctx context.Context, arg DeleteVlanParams) error {
	_, err := q.db.Exec(ctx, deleteVlan, arg.ID)
	return err
}

const getVlanByID = `-- name: GetVlanByID :one
SELECT id, name, vlan_id, description, is_active, created_at, updated_at
FROM vlans
WHERE id = $1
LIMIT 1
`

type GetVlanByIDParams struct {
	ID int64 `db:"id" json:"id"`
}

func (q *Queries) GetVlanByID(ctx context.Context, arg GetVlanByIDParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVlanByID, arg.ID)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VlanID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVlanByName = `-- name: GetVlanByName :one
SELECT id, name, vlan_id, description, is_active, created_at, updated_at
FROM vlans
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

type GetVlanByNameParams struct {
	Name string `db:"name" json:"name"`
}

func (q *Queries) GetVlanByName(ctx context.Context, arg GetVlanByNameParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVlanByName, arg.Name)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VlanID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVlans = `-- name: ListVlans :many
SELECT id, name, vlan_id, description, is_active, created_at, updated_at
FROM vlans
ORDER BY vlan_id, id
`

func (q *Queries) ListVlans(ctx context.Context) ([]Vlan, error) {
	rows, err := q.db.Query(ctx, listVlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vlan{}
	for rows.Next() {
		var i Vlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VlanID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVlan = `-- name: UpdateVlan :one
UPDATE vlans
SET
  name = $1,
  vlan_id = $2,
  description = $3,
  is_active = $4,
  updated_at = NOW()
WHERE id = $5
RETURNING id, name, vlan_id, description, is_active, created_at, updated_at
`

type UpdateVlanParams struct {
	Name        string `db:"name" json:"name"`
	VlanID      int32  `db:"vlan_id" json:"vlan_id"`
	Description string `db:"description" json:"description"`
	IsActive    bool   `db:"is_active" json:"is_active"`
	ID          int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateVlan(ctx context.Context, arg UpdateVlanParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, updateVlan,
		arg.Name,
		arg.VlanID,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i Vlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VlanID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
