// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vlans.sql

package db

import (
	"context"
)

const countVlans = `-- name: CountVlans :one
SELECT COUNT(*)
FROM vlans
`

func (q *Queries) CountVlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVlan = `-- name: CreateVlan :one
INSERT INTO vlans (
  vlan_id,
  name,
  description
) VALUES (
  $1,
  $2,
  $3
)
RETURNING vlan_id, name, description, created_at, updated_at
`

type CreateVlanParams struct {
	VlanID      int32  `db:"vlan_id" json:"vlan_id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateVlan(ctx context.Context, arg CreateVlanParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, createVlan, arg.VlanID, arg.Name, arg.Description)
	var i Vlan
	err := row.Scan(
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVlan = `-- name: DeleteVlan :exec
DELETE FROM vlans
WHERE vlan_id = $1
`

type DeleteVlanParams struct {
	VlanID int32 `db:"vlan_id" json:"vlan_id"`
}

func (q *Queries) DeleteVlan(ctx context.Context, arg DeleteVlanParams) error {
	_, err := q.db.Exec(ctx, deleteVlan, arg.VlanID)
	return err
}

const getVlanByName = `-- name: GetVlanByName :one
SELECT vlan_id, name, description, created_at, updated_at
FROM vlans
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

type GetVlanByNameParams struct {
	Name string `db:"name" json:"name"`
}

func (q *Queries) GetVlanByName(ctx context.Context, arg GetVlanByNameParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVlanByName, arg.Name)
	var i Vlan
	err := row.Scan(
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVlanByVlanID = `-- name: GetVlanByVlanID :one
SELECT vlan_id, name, description, created_at, updated_at
FROM vlans
WHERE vlan_id = $1
LIMIT 1
`

type GetVlanByVlanIDParams struct {
	VlanID int32 `db:"vlan_id" json:"vlan_id"`
}

func (q *Queries) GetVlanByVlanID(ctx context.Context, arg GetVlanByVlanIDParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, getVlanByVlanID, arg.VlanID)
	var i Vlan
	err := row.Scan(
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVlans = `-- name: ListVlans :many
SELECT vlan_id, name, description, created_at, updated_at
FROM vlans
ORDER BY vlan_id
`

func (q *Queries) ListVlans(ctx context.Context) ([]Vlan, error) {
	rows, err := q.db.Query(ctx, listVlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vlan{}
	for rows.Next() {
		var i Vlan
		if err := rows.Scan(
			&i.VlanID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVlan = `-- name: UpdateVlan :one
UPDATE vlans
SET
  vlan_id = $1,
  name = $2,
  description = $3,
  updated_at = NOW()
WHERE vlan_id = $4
RETURNING vlan_id, name, description, created_at, updated_at
`

type UpdateVlanParams struct {
	VlanID        int32  `db:"vlan_id" json:"vlan_id"`
	Name          string `db:"name" json:"name"`
	Description   string `db:"description" json:"description"`
	CurrentVlanID int32  `db:"current_vlan_id" json:"current_vlan_id"`
}

func (q *Queries) UpdateVlan(ctx context.Context, arg UpdateVlanParams) (Vlan, error) {
	row := q.db.QueryRow(ctx, updateVlan,
		arg.VlanID,
		arg.Name,
		arg.Description,
		arg.CurrentVlanID,
	)
	var i Vlan
	err := row.Scan(
		&i.VlanID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
