name: docker-publish
run-name: >-
  ${{
    github.event_name == 'workflow_dispatch' && format('Build {0} ({1}, manual)', github.event.repository.name, github.ref_name) ||
    startsWith(github.ref, 'refs/tags/') && format('Build {0} ({1})', github.event.repository.name, github.ref_name) ||
    format('Build {0} ({1})', github.event.repository.name, github.ref_name)
  }}

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: api
            image: ghcr.io/sbekti/intern-api
            file: ./Dockerfile
            cache_scope: intern-api
          - name: web
            image: ghcr.io/sbekti/intern-www
            file: ./web/Dockerfile
            cache_scope: intern-www
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      job-name-prefix: ${{ matrix.name }}
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: .
      file: ${{ matrix.file }}
      meta-images: ${{ matrix.image }}
      set-meta-labels: true
      cache: true
      cache-mode: max
      cache-scope: ${{ matrix.cache_scope }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
